import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "./components/header";
import Footer from "./components/footer";
import { ThemeProvider } from "./components/theme-provider";
import { Toaster } from "./components/ui/sonner";
import { redirect } from "next/navigation";
import { validateRequest } from "@/auth";

import "./prosemirror.css";
import "./globals.css";
import Navbar from "@/app/(main)/Navbar";
import SessionProvider from "@/app/(main)/SessionProvider";
import MenuBar from "@/app/(main)/MenuBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const session = await validateRequest();

//   if (!session.user) redirect("/login");
//   return (
//     <ThemeProvider
//       enableSystem
//       attribute="class"
//       defaultTheme="system"
//       disableTransitionOnChange
//     >
//       {/* <Header /> */}
//       <Navbar />
//       <main className="grow">{children}</main>
//       <Footer />
//       <Toaster position="top-center" />
//     </ThemeProvider>
//   );
// }

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await validateRequest();

  if (!session.user) redirect("/login");

  return (
    <SessionProvider value={session}>
      <div className="flex min-h-screen flex-col">
        <Navbar />
        <div className="mx-auto flex w-full max-w-7xl grow gap-5 p-5">
          <MenuBar className="sticky top-[5.25rem] hidden h-fit flex-none space-y-3 rounded-2xl bg-card px-3 py-5 shadow-sm sm:block lg:px-5 xl:w-80" />
          {children}
        </div>
        <MenuBar className="sticky bottom-0 flex w-full justify-center gap-5 border-t bg-card p-3 sm:hidden" />

        <Footer />
        <Toaster position="top-center" />
      </div>
    </SessionProvider>
  );
}
