import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "./components/header";
import Footer from "./components/footer";
import { ThemeProvider } from "./components/theme-provider";
import { Toaster } from "./components/ui/sonner";
import { redirect } from "next/navigation";
import { validateRequest } from "@/auth";

import "./prosemirror.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateRequest();

  if (!session.user) redirect("/login");
  return (
    <ThemeProvider
      enableSystem
      attribute="class"
      defaultTheme="system"
      disableTransitionOnChange
    >
      <Header />
      <main className="grow">{children}</main>
      <Footer />
      <Toaster position="top-center" />
    </ThemeProvider>
  );
}
